FROM java:openjdk-8-jre-alpine
LABEL Goal="Lunatech Labs - Challange" \
        Maintainer="Matheus Lozano Sanches" \
        Package="airports-assembly-1.1.0.jar"

ADD airports-assembly-1.1.0.jar /

CMD [ "java", "-jar", "airports-assembly-1.1.0.jar" ]
