FROM java:openjdk-8-jre-alpine
LABEL Goal="Lunatech Labs - Challange" \
        Maintainer="Matheus Lozano Sanches" \
        Package="countries-assembly-1.0.1.jar"

ADD countries-assembly-1.0.1.jar /

CMD [ "java", "-jar", "countries-assembly-1.0.1.jar" ]